export default function Settings() {
  return (
    <div>
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
      Settings
    </div>
  )
}