version: '3.9'
services:
  simm:
    image: webion/simm
    container_name: simm
    build:
      context: ..
      dockerfile: docker/nx.website.dockerfile
      args:
        - target=simm-imballaggi

    environment:
      - VIRTUAL_HOST=simm.webion.it
    networks:
      - frontend

networks:
  frontend:
    name: frontend