import { BlogArticle } from '../../components/cards/BlogArticleCard';

export const articles: BlogArticle[] = [
  {
    id: 1,
    name: 'nome',
    title: '3 vantaggi dei servizi di sviluppo software personalizzati',
    category: 'Business',
    readingTime: 5,
    date: '21 Mag 2021',
    image: '/assets/images/websites.jpg',
    article:
      "Molte aziende scelgono servizi di sviluppo software personalizzati per creare un vantaggio unico rispetto alla concorrenza. Disponendo di software specifico su misura per i loro processi aziendali, le organizzazioni possono migliorare il flusso di lavoro e le prestazioni. <br /><br />Ecco tre vantaggi che la tua azienda potrebbe ottenere lavorando con una società di sviluppo software personalizzato.<br /><br /> <b>1. Flusso di lavoro semplificato</b><br /> Il primo vantaggio di lavorare con una società di sviluppo software personalizzato è che puoi semplificare il flusso di lavoro della tua organizzazione. Avendo sviluppato un software specifico per le tue esigenze aziendali, puoi eliminare tutti i passaggi non necessari nel tuo processo. Ciò porterà a un ambiente di lavoro più efficiente e a prestazioni migliori da parte dei dipendenti. <b><br /><br />2. Servizio clienti migliorato</b><br /> Un altro vantaggio di lavorare con una società di sviluppo software personalizzato è il miglioramento del servizio clienti. Disponendo di un software progettato per soddisfare le esigenze specifiche dei tuoi clienti, puoi fornire loro un'esperienza migliore. Ciò porterà a una maggiore fedeltà e tassi di soddisfazione dei clienti più elevati. <b><br /><br />3. Aumento delle vendite</b><br /> Il terzo vantaggio di lavorare con una società di sviluppo software personalizzato è l'aumento delle vendite. Avendo un vantaggio unico sulla concorrenza, sarai in grado di attirare più clienti. Ciò porterà ad un aumento delle entrate e della redditività per la tua attività. <br /><br /> I servizi di sviluppo software personalizzati possono fornire alla tua azienda molti vantaggi, tra cui un flusso di lavoro ottimizzato, un servizio clienti migliore e un aumento delle vendite. Se stai cercando modi per dare alla tua azienda un vantaggio competitivo, lavorare con un'azienda di sviluppo software personalizzato è un'ottima opzione da considerare.",
  },
  {
    id: 2,
    name: 'nome-2',
    title: 'Lorem Ipsum',
    category: 'Business',
    readingTime: 5,
    date: '21 Mag 2021',
    image: '/assets/images/websites.jpg',
    article:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dictum feugiat aliquam. Vivamus id arcu vitae tellus ultricies tincidunt. Phasellus varius condimentum sapien in dignissim. In dapibus in leo sed pellentesque. Mauris sit amet mattis risus. Vestibulum lacinia rhoncus justo. Cras congue tortor fringilla pellentesque malesuada. Maecenas nec neque risus. Proin porta sed augue quis condimentum. Vestibulum ullamcorper odio vitae ex facilisis cursus. Donec augue felis, ultricies sed ullamcorper et, fermentum eget velit. Sed vel orci quis diam hendrerit fermentum non tincidunt libero. Aliquam justo quam, rutrum ut pretium ac, rhoncus sed dolor. Etiam non est ut arcu condimentum elementum eu non nibh. Nulla a risus sed libero iaculis dictum.<br/><br/> In ultrices tortor eu massa dictum, a vulputate tellus rhoncus. Vestibulum nec erat gravida massa pellentesque dapibus. Proin tempus mauris tortor, in posuere nunc lobortis vitae. Donec sodales augue nec magna auctor aliquet. Phasellus sed justo turpis. Fusce at augue sed quam luctus dapibus sit amet sit amet arcu. Quisque imperdiet, dolor vel aliquet consectetur, dolor ex lacinia sem, vel convallis ligula mi eu neque. Sed in tellus elit. Sed euismod massa sit amet nunc auctor, vel faucibus sem consequat. Vivamus rhoncus sed nisi sit amet eleifend. Etiam id tellus non felis ultricies facilisis nec vel ante. Fusce fringilla diam nibh, quis condimentum est vehicula eget. Aenean malesuada tortor vitae mi aliquam, sit amet efficitur erat vehicula. Aenean pellentesque turpis quis tortor congue vestibulum. Vestibulum euismod luctus elementum. Aliquam tempor tincidunt magna ac lacinia.<br/><br/> Cras dolor velit, auctor eu ante sed, blandit posuere tortor. Vivamus risus libero, pharetra vitae ullamcorper id, pharetra in arcu. Nunc tempor, est pretium hendrerit dignissim, lectus mi consequat tellus, ac pulvinar ligula odio tristique magna. Vivamus lacus arcu, convallis at arcu et, faucibus ultrices risus. Nulla vehicula, nunc eget gravida dictum, nulla dui porta diam, non feugiat arcu neque cursus mauris. Ut magna metus, dictum non feugiat ut, pellentesque sit amet leo. Vestibulum sodales libero in ultrices semper. Quisque blandit nisl ut suscipit elementum. Mauris varius quam aliquet, dapibus nibh non, pellentesque ipsum. Quisque vulputate gravida convallis. Aenean nec feugiat ante. Maecenas scelerisque nisi est, vel vestibulum elit mollis eget. Mauris ut sapien a neque faucibus efficitur vitae dapibus ipsum. Ut tristique ex lectus, sit amet placerat libero varius id. Maecenas dictum dui a mi accumsan, eu finibus nisi luctus. Mauris faucibus suscipit lorem, et pharetra sem semper et.<br/><br/>',
  },
  {
    id: 3,
    name: 'nome-3',
    title: 'Lorem Ipsum',
    category: 'Business',
    readingTime: 5,
    date: '21 Mag 2021',
    image: '/assets/images/websites.jpg',
    article:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dictum feugiat aliquam. Vivamus id arcu vitae tellus ultricies tincidunt. Phasellus varius condimentum sapien in dignissim. In dapibus in leo sed pellentesque. Mauris sit amet mattis risus. Vestibulum lacinia rhoncus justo. Cras congue tortor fringilla pellentesque malesuada. Maecenas nec neque risus. Proin porta sed augue quis condimentum. Vestibulum ullamcorper odio vitae ex facilisis cursus. Donec augue felis, ultricies sed ullamcorper et, fermentum eget velit. Sed vel orci quis diam hendrerit fermentum non tincidunt libero. Aliquam justo quam, rutrum ut pretium ac, rhoncus sed dolor. Etiam non est ut arcu condimentum elementum eu non nibh. Nulla a risus sed libero iaculis dictum.<br/><br/> In ultrices tortor eu massa dictum, a vulputate tellus rhoncus. Vestibulum nec erat gravida massa pellentesque dapibus. Proin tempus mauris tortor, in posuere nunc lobortis vitae. Donec sodales augue nec magna auctor aliquet. Phasellus sed justo turpis. Fusce at augue sed quam luctus dapibus sit amet sit amet arcu. Quisque imperdiet, dolor vel aliquet consectetur, dolor ex lacinia sem, vel convallis ligula mi eu neque. Sed in tellus elit. Sed euismod massa sit amet nunc auctor, vel faucibus sem consequat. Vivamus rhoncus sed nisi sit amet eleifend. Etiam id tellus non felis ultricies facilisis nec vel ante. Fusce fringilla diam nibh, quis condimentum est vehicula eget. Aenean malesuada tortor vitae mi aliquam, sit amet efficitur erat vehicula. Aenean pellentesque turpis quis tortor congue vestibulum. Vestibulum euismod luctus elementum. Aliquam tempor tincidunt magna ac lacinia.<br/><br/> Cras dolor velit, auctor eu ante sed, blandit posuere tortor. Vivamus risus libero, pharetra vitae ullamcorper id, pharetra in arcu. Nunc tempor, est pretium hendrerit dignissim, lectus mi consequat tellus, ac pulvinar ligula odio tristique magna. Vivamus lacus arcu, convallis at arcu et, faucibus ultrices risus. Nulla vehicula, nunc eget gravida dictum, nulla dui porta diam, non feugiat arcu neque cursus mauris. Ut magna metus, dictum non feugiat ut, pellentesque sit amet leo. Vestibulum sodales libero in ultrices semper. Quisque blandit nisl ut suscipit elementum. Mauris varius quam aliquet, dapibus nibh non, pellentesque ipsum. Quisque vulputate gravida convallis. Aenean nec feugiat ante. Maecenas scelerisque nisi est, vel vestibulum elit mollis eget. Mauris ut sapien a neque faucibus efficitur vitae dapibus ipsum. Ut tristique ex lectus, sit amet placerat libero varius id. Maecenas dictum dui a mi accumsan, eu finibus nisi luctus. Mauris faucibus suscipit lorem, et pharetra sem semper et.<br/><br/>',
  },
  {
    id: 4,
    name: 'nome-4',
    title: 'Lorem Ipsum',
    category: 'Business',
    readingTime: 5,
    date: '21 Mag 2021',
    image: '/assets/images/websites.jpg',
    article:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dictum feugiat aliquam. Vivamus id arcu vitae tellus ultricies tincidunt. Phasellus varius condimentum sapien in dignissim. In dapibus in leo sed pellentesque. Mauris sit amet mattis risus. Vestibulum lacinia rhoncus justo. Cras congue tortor fringilla pellentesque malesuada. Maecenas nec neque risus. Proin porta sed augue quis condimentum. Vestibulum ullamcorper odio vitae ex facilisis cursus. Donec augue felis, ultricies sed ullamcorper et, fermentum eget velit. Sed vel orci quis diam hendrerit fermentum non tincidunt libero. Aliquam justo quam, rutrum ut pretium ac, rhoncus sed dolor. Etiam non est ut arcu condimentum elementum eu non nibh. Nulla a risus sed libero iaculis dictum.<br/><br/> In ultrices tortor eu massa dictum, a vulputate tellus rhoncus. Vestibulum nec erat gravida massa pellentesque dapibus. Proin tempus mauris tortor, in posuere nunc lobortis vitae. Donec sodales augue nec magna auctor aliquet. Phasellus sed justo turpis. Fusce at augue sed quam luctus dapibus sit amet sit amet arcu. Quisque imperdiet, dolor vel aliquet consectetur, dolor ex lacinia sem, vel convallis ligula mi eu neque. Sed in tellus elit. Sed euismod massa sit amet nunc auctor, vel faucibus sem consequat. Vivamus rhoncus sed nisi sit amet eleifend. Etiam id tellus non felis ultricies facilisis nec vel ante. Fusce fringilla diam nibh, quis condimentum est vehicula eget. Aenean malesuada tortor vitae mi aliquam, sit amet efficitur erat vehicula. Aenean pellentesque turpis quis tortor congue vestibulum. Vestibulum euismod luctus elementum. Aliquam tempor tincidunt magna ac lacinia.<br/><br/> Cras dolor velit, auctor eu ante sed, blandit posuere tortor. Vivamus risus libero, pharetra vitae ullamcorper id, pharetra in arcu. Nunc tempor, est pretium hendrerit dignissim, lectus mi consequat tellus, ac pulvinar ligula odio tristique magna. Vivamus lacus arcu, convallis at arcu et, faucibus ultrices risus. Nulla vehicula, nunc eget gravida dictum, nulla dui porta diam, non feugiat arcu neque cursus mauris. Ut magna metus, dictum non feugiat ut, pellentesque sit amet leo. Vestibulum sodales libero in ultrices semper. Quisque blandit nisl ut suscipit elementum. Mauris varius quam aliquet, dapibus nibh non, pellentesque ipsum. Quisque vulputate gravida convallis. Aenean nec feugiat ante. Maecenas scelerisque nisi est, vel vestibulum elit mollis eget. Mauris ut sapien a neque faucibus efficitur vitae dapibus ipsum. Ut tristique ex lectus, sit amet placerat libero varius id. Maecenas dictum dui a mi accumsan, eu finibus nisi luctus. Mauris faucibus suscipit lorem, et pharetra sem semper et.<br/><br/>',
  },
];
