name: CI
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
      - uses: nrwl/nx-set-shas@v2
      - run: npm ci

      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - run: npx nx affected --target=build --parallel=3
