name: CI
on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - uses: nrwl/nx-set-shas@v2
      - name: install
      - run: npm ci

      - name: lint
      - run: npx nx workspace-lint
      - run: npx nx affected --target=lint --parallel=3
      
      - name: test
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      
      - name: build
      - run: npx nx affected --target=build --parallel=3
