name: Publish package to Npm Packages
on:
  push:
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org/'
          scope: 'wui'


      - run: pnpm install --frozen-lockfile
      - run: pnpm config set access public
      - run: pnpm publish packages/@wui/core/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
