name: Publish package to GitHub Packages
on:
  push:
      
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'

      - run: pnpm config set registry https://npm.pkg.github.com
      - run: pnpm install --frozen-lockfile
      - run: pnpm publish packages/@wui/core/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
