name: publish
on:
  push:
    branches:
      - main
      - release
  
  pull_request:

jobs:
  publish:
    runs-on: [self-hosted, publish]
    steps:
      - run: git config --global --add safe.directory /home/webion/server/whub
      - run: bash /home/webion/server/publish_wsite.sh
