name: publish
on:
  push:
    branches:
      - main
      - release

  pull_request:

jobs:
  publish:
    runs-on: [self-hosted, publish]
    steps:
      - run: cd /home/webion/server/
      - run: bash publish_wsite.sh
